Entity/Rank.php
<?php

namespace Trendix\RankBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Trendix\AdminBundle\Entity\User;
use Trendix\AdminBundle\EventListener\DiscriminatorEntry;
/*
 * @ORM\DiscriminatorMap{
 *     "EVALUATIONFORM" = "Trendix\RankBundle\Entity\EvaluationForm",
 *     "SUPPLIERCLASSIFICATION" = "Trendix\RankBundle\Entity\SupplierClassification",
 *     "RECURRENTFORM" = "Trendix\RankBundle\Entity\RecurrentForm"
 * }
 */
/**
 * Rank
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Trendix\RankBundle\Entity\Repository\RankRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name = "type", type = "string")
 * @DiscriminatorEntry(value = "rank")
 */
class Rank
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var Rank
     * @ORM\OneToOne(targetEntity="Trendix\RankBundle\Entity\Rank")
     */
    protected $parent;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Trendix\RankBundle\Entity\Poll\Poll", mappedBy="rank")
     */
    protected $polls;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $created_at;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    protected $updated_at;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Trendix\RankBundle\Entity\Section", mappedBy="rank", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"position" = "ASC"})
     */
    protected $sections;

    /**
     * @var boolean
     *
     * @ORM\Column(name="draft", type="boolean")
     */
    protected $draft;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->sections = new ArrayCollection();
        $this->sections->add(new Section());
        $this->polls = new ArrayCollection();
        $this->draft = true;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Rank
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param Rank $parent
     * @return Rank
     */
    public function setParent(Rank $parent)
    {
        $this->parent = $parent;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getPolls()
    {
        return $this->polls;
    }

    /**
     * @param ArrayCollection $polls
     * @return Rank
     */
    public function setPolls(ArrayCollection $polls): Rank
    {
        $this->polls = $polls;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param \DateTime $created_at
     * @return Rank
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param \DateTime $updated_at
     * @return Rank
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getSections()
    {
        return $this->sections;
    }

    /**
     * @param ArrayCollection $sections
     * @return Rank
     */
    public function setSections($sections)
    {
        $this->sections = $sections;
        return $this;
    }

    /**
     * @param Section $section
     *
     * @return $this
     */
    public function addSection(Section $section)
    {
        $section->setRank($this);
        $this->sections->add($section);

        return $this;
    }

    /**
     * @param Section $section
     *
     * @return $this
     */
    public function removeSection(Section $section)
    {
        if ($this->sections->contains($section)) {
            $this->sections->removeElement($section);
        }

        return $this;
    }

    /**
     * @return bool
     */
    public function isDraft()
    {
        return $this->draft;
    }

    /**
     * @param bool $draft
     * @return Rank
     */
    public function setDraft($draft)
    {
        $this->draft = $draft;
        return $this;
    }

    public function __toString()
    {
        return (string) $this->id;
    }

    public function cloneWithParent(Rank $Rank)
    {
        $Rank->setParent($Rank);
        return clone $Rank;
    }

    public function __clone() {
        if ($this->id) {
            // Eliminamos el id para que se genere una nueva fila en base de datos
            $this->id = null;
            $this->created_at = new \DateTime();

            // clonamos las secciones hijas
            $newSections = new ArrayCollection();
            foreach ($this->sections as $section) {
                $newSection = clone $section;
                $newSection->setRank($this);
                $newSection->setParent($section);
                $newSections->add($newSection);
            }
            $this->sections = $newSections;
        }
    }
}

Resources/views/evaluations/category/EvaluationForm.html.twig
{#
Esta subplantilla muestra el contenido de una vesion de un formulario de evaluación para una subcategoría específica
Se debe invocar con un include y debe recibir como parámetros
    subcategoria: La subcategoría a la que pertenece la version del formulario de evaluación
    evaluationVersion: La version del forulario de evaluación
    readonly: hará que la plantilla se readmode o editmode dependiendo de su valor.
#}

{% if readonly is not defined %}
    {% set readonly = false %}
{% endif %}

{% extends '::simpleLayout.html.twig' %}

{% block more_styles %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/Admin/form-validator/form-validator.css') }}" />
{% endblock %}

{% set titulo = subcategoria.nombre %}

{% block title %}
    {{ titulo }} - {{ parent() }}
{% endblock title %}

{% block content_body %}
    {{ form_start(form, {attr: {id: 'versionForm'}}) }}
    {{ form_widget(form.subcategoria) }}
    {{ form_widget(form.evaluationForm) }}
    {{ form_widget(form.author) }}
    {{ form_widget(form._token) }}
    {% set launchmentText = 'evaluations.launchment_ready'|trans %}
    {% set approvalText = 'evaluations.pending_evaluation'|trans %}
    {% set status = 'warning' %}


    {% if evaluationVersion.evaluationForm.createdAt is not null %}
        {% set  status = 'success' %}
        {% set launchmentText = 'evaluations.launched'|trans ~ ' (' ~ evaluationVersion.evaluationForm.createdAt|formatTrendixDate ~ ')' %}
    {% endif %}

    {% if evaluationVersion.publishAt is not null %}
        {% set status = ' info' %}
        {% set approvalText = 'evaluations.approved_evaluation'|trans ~ ' (' ~ evaluationVersion.publishAt|formatTrendixDate ~ ')' %}
    {% else %}

    {% endif %}

    {% set leftData = launchmentText ~ ' - ' ~ approvalText %}

    {% include ':helpers:StatusBar.html.twig' with {'leftData': leftData, 'status': status} only %}

    {% for section in form.sections %}
        {% embed 'TrendixRankBundle:evaluations:SectionBlockLayout.html.twig' with
        {
            'section': section,
            'weight': section.weight.vars.value,
        }  %}

            {% block evaluation_section_title %}
                {{ section.section.vars.data.title }}
            {% endblock %}

            {% block evaluation_section_description %}
                {{ section.section.vars.data.description }}
            {% endblock %}

            {% block evaluation_section_weight %}
                {% if readonly is defined and readonly %}
                    <span class="label label-default">{{ weight }} %</span>
                {% else %}
                {{ form_widget(section.weight) }}
                <input type="hidden" id="{{ section.section.vars.id }}" name="{{ section.section.vars.full_name }}" value="{{ section.section.vars.data.id }}">
                {{ form_widget(section.visible) }}
                {% endif %}
            {% endblock %}

            {% block evaluation_section_questions %}
                {% include 'TrendixRankBundle:evaluations/category:EvaluationFormQuestions.html.twig' with {
                    'questions': form.criteria,
                    'section': section
                } %}
            {% endblock %}
        {% endembed %}
    {% endfor %}

    {% if classificationSection is defined %}
        {% if classificationSection is null %}
            <div class="d-none">
                {{ form_widget(form.classificationWeight, {attr: {value: '0'}}) }}
            </div>
        {% else %}
            <div class="block section">
                <div class="block-header">
                    {{ classificationSection.title }}
                    <div class="block-actions">
                        {{ form_widget(form.classificationWeight) }}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endif %}
    {{ form_end(form, {render_rest: false}) }}
{% endblock %}

{% block action_buttons %}
    <a class="btn btn-info" title="{{ 'str_volver'|trans }}" href="{{ path('list_evaluation_version') }}"><i class="icon icon-arrow-left"></i></a>
    {% if evaluationVersion.publishAt is null %}
    <a class="btn btn-warning" title="{{ 'str_aprobar'|trans }}" data-action="AprobarVersionEvaluacion"><i class="icon icon-check"></i></a>
    {% endif %}
    {% if not readonly %}
    <a class="btn btn-success" title="{{ 'str_guardar'|trans }}" data-action="guardarVersionEvaluacion"><i class="icon icon-save"></i></a>
    {% endif %}
{% endblock %}

{% block more_scripts %}
    {{ parent() }}
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
    {% include 'TrendixRankBundle:evaluations:DesignerCriterionFunctionality.html.twig' %}

    <script>
        $('#versionForm').validate();

        {% if not readonly %}
        function action_toggleQuestionVisibility()
        {
            var active = parseInt($action_button.find('input').val());

            $action_button.closest('tr').toggleClass('enabled', active);
            $action_button.closest('tr').toggleClass('disabled', (active + 1) % 2);
            $action_button.find('i.icon').toggleClass('zmdi zmdi-eye-off', active);
            $action_button.find('i.icon').toggleClass('zmdi zmdi-eye', (active + 1) % 2);
            if ($action_button.find('input[type="checkbox"]').is(':checked')) {
                $action_button.find('input[type="checkbox"]').prop('checked', false);
                $action_button.find('input[type="checkbox"]').removeAttr('checked');
            } else {
                $action_button.find('input[type="checkbox"]').prop('checked', true);
                $action_button.find('input[type="checkbox"]').attr('checked', 'checked');
            }

            checkSection();
        }

        /**
         * Comprueba si una seccion es visible o no y, si no lo es, coloca su peso a 0
         */
        function checkSection()
        {
            var $sectionBlock = $action_button.closest('.block.section');
            var $sectionWeightInput = $sectionBlock.find('.block-actions input[id*="_weight"]');
            var $sectionVisibleInput = $sectionBlock.find('.block-actions input[id*="_visible"]');

            var isSectionVisible = false;
            $sectionBlock.find('table input[type="checkbox"]').each(function() {
                if ($(this).is(':checked')) {
                    isSectionVisible = true;
                }
            });

            if (!isSectionVisible) {
                $sectionVisibleInput.prop('checked', false);
                $sectionVisibleInput.removeAttr('checked');
                $sectionWeightInput.val('0');
                $sectionWeightInput.attr('readonly', 'readonly');
            } else {
                $sectionVisibleInput.prop('checked', true);
                $sectionVisibleInput.attr('checked', 'checked');
                $sectionWeightInput.removeAttr('readonly');
            }
        }

        function action_guardarVersionEvaluacion()
        {
            var isValid = $('#versionForm').isValid();

            if (isValid) {
                $.ajax({
                    url: '{{ path('save_evaluation_version', {id: evaluationVersion.id}) }}',
                    type: 'post',
                    data: $('#versionForm').serialize()
                }).done(function(data) {
                    handleResponse(data);
                    if (data.type == 'OK') {
                        window.location.href = '{{ path('list_evaluation_version') }}';
                    }
                });
            }
        }
        {% endif %}

        function action_AprobarVersionEvaluacion() {
            var isValid = $('#versionForm').isValid();

            if (isValid) {
                $.ajax({
                    url: '{{ path('save_evaluation_version', {id: evaluationVersion.id}) }}',
                    type: 'post',
                    data: $('#versionForm').serialize() + '&aprobar=true'
                }).done(function (data) {
                    handleResponse(data);
                    if (data.type == 'OK') {
                        window.location.href = '{{ path('list_evaluation_version') }}';
                    }
                });
            }
        }
    </script>
{% endblock %}

Resources/views/evaluations/category/EvaluationFormQuestions.html.twig
{#
Esta subplantilla forma parte de EvaluationFormSection.html.twig
Recibe como parametros:
 questions: Lista de preguntas de una seccion
 visibilities: Array con las visibilidades de los criterion/question
 readonly: booleano que indica si la plantilla es editable o no
#}

{% if readonly is not defined %}
    {% set readonly = true %}
{% endif %}

{#
{% import 'helpers/QuestionIcons.html.twig' as icons %}
#}
<!-- evaluations/category/EvaluationFormQuestions begin -->
<table class="table table-striped table-responsive selectable questions-list">
    <thead>
    <tr>
        <th colspan="2">{{ 'evaluations.questions'|trans }}</th>
        <th>{{ 'str_informes_tipo'|trans }}</th>
        <th>{{ 'str_peso'|trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for question in questions if question.criterion.vars.data.section.id == section.section.vars.data.id %}
        <tr
                data-id="{{ question.vars.data.id }}"
                {% if not question.visible.vars.data %}
                    class="disabled"
                {% else %}
                    class="enabled"
                {% endif %}
        >
            <td style="width: 24px;" {% if readonly %}
                    class="disabled"
                    {% else %}
                    class="enabled" data-action="toggleQuestionVisibility" data-id="{{ question.vars.data.id }}{% endif %}">
                {#{{ icons.QuestionVisibilityIcon(question.visible.vars.data) }}#}
                {{ form_widget(question.visible) }}
                <input type="hidden" id="{{ question.criterion.vars.id }}" name="{{ question.criterion.vars.full_name }}" value="{{ question.criterion.vars.data.id }}">

            </td>
            <td>{{ question.criterion.vars.data.title }}</td>
            <td style="width: 48px;" class="text-center">{#{{ icons.QuestionTypeIcon(question.criterion.vars.data.name) }}#}</td>
            <td style="width: 48px;" class="text-center"><span class="weight">{{ question.criterion.vars.data.weight }}</span></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<!-- evaluations/category/EvaluationFormQuestions end -->

Resources/views/evaluations/category/EvaluationPanel.html.twig
{#
[#150216660] - Rank - **VIEWS** - CATEGORIES
Esta vista muestra el listado de Versiones de Evaluaciones para una categoría y deberá ser incluida en la
vista de una subcategoría.

Recibirá como parámetro un listado (array) de Versiones de Evaluación
Cada elemento del listado tendrá dos acciones asociadas:
 * ver versión: Que tendrá la capacidad de acceder a la pantalla de EvaluationForm - Read Mode
 * Editar versión: Llevará a la pantalla de EvaluationsForm - Edit Mode únicamente para la versión que esté pendiente.
#}

{% import _self as status %}

<div class="block">
    <div class="block-header">{{ 'evaluations.form_versions'|trans }}</div>
    <div class="block-content no-padding">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{{ 'str_estado'|trans }}</th>
                    <th>{{ 'evaluations.author'|trans }}</th>
                    <th>{{ 'str_subcategoria'|trans }}</th>
                    <th>{{ 'evaluations.evaluation_form_launchment_date'|trans }}</th>
                    <th>{{ 'str_acciones'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for evaluationVersion in evaluationVersions %}
                <tr>
                    <td>{{ status.approval(evaluationVersion.publishAt) }}</td>
                    <td>{{ evaluationVersion.author }}</td>
                    <td>{{ evaluationVersion.subcategoria }}</td>
                    <td>{{ status.launchment(evaluationVersion.evaluationform.updatedat) }}</td>
                    <td class="actions">
                        {% if evaluationVersion.id is not null %}
                        <a class="btn btn-icon btn-link" href="{{ path('view_evaluation_version', {id: evaluationVersion.id}) }}"><i class="zmdi zmdi-eye"></i></a>
                        {% endif %}

                        {% if evaluationVersion.id is null or evaluationVersion.publishAt is not null %}
                        <a title="{{ 'str_generico_boton_nuevo'|trans }}" class="btn btn-icon btn-link btn-success" href="{{ path('new_evaluation_version', {subcategory: evaluationVersion.subcategoria.id}) }}"><i class="icon-plus"></i></a>
                        {% else %}
                        <a title="{{ 'str_editar'|trans }}" class="btn btn-icon btn-link" href="{{ path('edit_evaluation_version', {id: evaluationVersion.id}) }}"><i class="zmdi zmdi-edit"></i></a>
                        {% endif %}

                        {% if evaluationVersion.id is not null %}
                        <a title="{{ 'str_duplicar'|trans }}" class="btn btn-icon btn-link" href="javascript:void(0);" data-action="selectCategoryModal" data-id="{{ evaluationVersion.id }}"><i class="zmdi zmdi-copy"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{# Muestra el estado de aprobación y la fecha de aprobación si procede #}
{% macro approval(date) %}
    {% if date is null %}
        {% set approvalStatus = 'evaluations.pending'|trans %}
    {% else %}
        {% set approvalStatus = 'evaluations.approved'|trans ~ ' - ' ~ date|formatTrendixDate %}
    {% endif %}

    {{ approvalStatus }}
{% endmacro %}

{# Muestra la fecha de lanzamiento de una evaluación #}
{% macro launchment(date) %}
    {% if date is null %}
        {% set launchmentStatus = 'evaluations.ready'|trans %}
    {% else %}
        {% set launchmentStatus = date|formatTrendixDate %}
    {% endif %}

    {{ launchmentStatus }}
{% endmacro %}

Resources/views/evaluations/category/VersionsModalPrompt.html.twig
<!-- evaluations/category/VersionsModalPrompt begin -->
<div id="VersionsModalPrompt" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="VersionsModalPromptHeader">{{ 'evaluations.approve_form_subcategory_version'|trans }}</h3>
            </div>
            <div class="modal-body">
                {% if versions|length == 1 %} {# Si sólo hay una versión solo puede ser la propia del usuario #}
                    <p>{{ 'evaluations.approve_your_weightings_and_visibilities'|trans }}</p>
                {% else %}
                    {% if SelectedVersion is null %} {# Si hay más de una versión y no hay seleccionada #}
                        <p>{{ 'evaluations.select_weightings_and_visibilities'|trans }}</p>
                    {% if SelectedVersion.author == trendix_usuario %} {# Si la seleccionada es la del usuario #}
                        <p>{{ 'evaluations.approve_your_weightings_and_visibilities'|trans }}</p>
                    {% else %} {# Si se selecciona la versión de otro usuario#}
                        <p>{{ 'evaluations.approve_user_weightings_and_visibilities'|trans({'%name%': SelectedVersion.author}) }}</p>
                    {% endif %}
                {% endif %}

            </div>
            <div class="modal-footer">
                <a href="javascript:void(0);" class="btn" data-dismiss="modal" aria-hidden="true">{{ 'str_cancelar'|trans }}</a>
                {% if SelectedVersion is null %}
                <a href="javascript:void(0);" class="btn btn-warning">{{ 'evaluation.select_version'|trans }}</a>
                {% else %}
                <a href="javascript:void(0);" class="btn btn-primary">{{ 'str_aprobar'|trans }}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- evaluations/category/VersionsModalPrompt end -->

Resources/views/evaluations/category/list.html.twig
{% extends '::simpleLayout.html.twig' %}

{% set titulo = 'evaluations.form_versions'|trans %}

{% block content_body %}
{% include '@TrendixRank/evaluations/category/EvaluationPanel.html.twig' with {evaluationVersions: versions} %}

<div id="SelectCategoryModal" class="modal hide fade" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="myModalLabel">{{ 'evaluations.seleccionar_subcategorias'|trans }}</h3>
            </div>
            <div class="modal-body no-padding">
                <table class="table table-striped selectable">
                {% for c in subcategorias %}
                    <tr data-action="toggleSelect" data-id="{{ c.id }}"><td>{{ c }}</td></tr>
                {% endfor %}
                </table>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">{{ 'str_cancelar'|trans }}</button>
                <button id="duplicateVersionModalBtn" data-action="overwriteVersionsModal" class="btn btn-primary">{{ 'str_seleccionar'|trans }}</button>
            </div>
        </div>
    </div>
</div>

{% include 'TrendixRankBundle:Modals:warningTemplate.html.twig' with {
    id: 'OverwriteVersions',
    header: 'str_generico_aviso_atencion',
    body: 'evaluations.versions_overwrite',
    action: 'duplicateVersion'
} %}

{% endblock %}

{% block more_scripts %}
    {{ parent() }}
    <script>
        var selections = [];
        function action_toggleSelect()
        {
            $action_button.toggleClass('selected');
            selections = [];
            $('#SelectCategoryModal table tr').each(function() {
               if ($(this).hasClass('selected')) {
                   selections.push($(this).data('id'));
               }
            });
        }

        function action_selectCategoryModal()
        {
            $('#btnModalOverwriteVersions').data('origin', $action_button.data('id'));
            $('#SelectCategoryModal').modal('show');
        }

        function action_overwriteVersionsModal()
        {
            $('#SelectCategoryModal').modal('hide');
            $('#modalOverwriteVersions').modal('show');
        }

        function action_duplicateVersion()
        {
            var datos = {
                subcategories: selections,
                origin: $action_button.data('origin')
            };

            $.ajax({
                type: 'post',
                url: '{{ path('duplicate_evaluation_version') }}',
                data: datos
            }).done(function(data) {
                handleResponse(data);
                setTimeout(window.location.reload(), 1000);
            });
        }
    </script>
{% endblock %}