Form/RankType.php
<?php

namespace Trendix\RankBundle\Form;

use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Trendix\AdminBundle\Entity\User;
use Trendix\RankBundle\Entity\Rank;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RankType extends AbstractType
{
    /**
     * @var User
     */
    private $user;

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $this->user = $options['user'];

        $builder
            ->add('sections', CollectionType::class, [
                    'type'			=> SectionType::class,
                    'allow_add'		=> true,
                    'allow_delete'	=> true,
                    'label' => 'str_bloques',
                    'prototype_name' => '__block__',
                    'by_reference' => false,
                    'entry_options' => ['em' => $options['em']]
                ]
            )
            ->addEventListener(FormEvents::SUBMIT, array($this, 'onSubmit'))
        ;

        $builder->add('draft', HiddenType::class, [
            'data' => $options['draft'],
            'empty_data' => $options['draft']
        ]);
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Trendix\RankBundle\Entity\Rank',
            'draft' => true
        ));

        $resolver->setRequired(['user', 'em']);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'rank';
    }

    public function onSubmit(FormEvent $event)
    {
        $rank = $event->getData();
        $this->userManagement($rank);
    }

    protected function userManagement(Rank $rank = null)
    {
        if (null === $rank) {
            return false;
        }

        if (null === $rank->getCreatedBy()) {
            $rank->setCreatedAt(new \DateTime());
            $rank->setCreatedBy($this->user);
        }

        $rank->setUpdatedAt(new \DateTime());
        $rank->setUpdatedBy($this->user);
    }
}

Resources/views/evaluations/provider/results/AnswerResultLayout.html.twig
{#
Esta sub plantilla muestra la estructura necesaria para una respuesta. También es capaz de detectar de forma dinámica el tipo de pregunta
y renderizar su respuesta correctamente.
Parámetros:
    - Question: La pregunta a mostrar su respuesta
    - Answer: La respuesta a la pregunta Question.
#}

<div class="answer-result">
    <div class="answer-title">
        <i class="icon icon-info tooltip" title="{{ question.description }}"></i> {{ question.title }}
    </div>

    <div class="answer">
        {% if answer is null %}
            <div class="label">{{ 'evaluations.pending'|trans }}</div>
        {% else %}
            {% include 'evaluations/provider/results/' ~ {{ question.type }} ~ 'Result.html.twig' with {'answer': answer} %}
        {% endif %}
    </div>

</div>

Resources/views/evaluations/provider/results/FilesResult.html.twig
<!-- Evaluation/provider/results/FileResult begin -->
<ul class="list">
    {% for file in answer.files %}
        <li><a href="{{ path('descargar_fichero', {'id': file.md5}) }}">{{ file.name }}</a></li>
    {% endfor %}
</ul>
<!-- Evaluation/provider/results/FileResult end -->

Resources/views/evaluations/provider/results/MultipleOptionsResult.html.twig
<!-- Evaluation/provider/results/MultipleOptionsResult begin -->
{% for option in answer.options %}
    <div class="option disabled">{{ option.value }}</div>
{% endif %}
<!-- Evaluation/provider/results/MultipleOptionsResult end -->

Resources/views/evaluations/provider/results/NumberResult.html.twig
<!-- Evaluation/provider/results/NumberResult begin -->
{{ answer.value }}
<!-- Evaluation/provider/results/NumberResult end -->

Resources/views/evaluations/provider/results/RangeResult.html.twig
{{ answer.value }}

Resources/views/evaluations/provider/results/SingleOptionResult.html.twig
<!-- Evaluation/provider/results/SingeOptionResult begin -->
{% for option in answer.options %}
    <div class="option disabled">{{ option.value }}</div>
{% endif %}
<!-- Evaluation/provider/results/SingeOptionResult end -->

Resources/views/evaluations/provider/results/TextResult.html.twig
<!-- Evaluation/provider/results/TextResult begin -->
{{ answer.value }}
<!-- Evaluation/provider/results/TextResult end -->