Entity/Criterion/Option.php
<?php

namespace Trendix\RankBundle\Entity\Criterion;
use Doctrine\ORM\Mapping as ORM;
use Trendix\RankBundle\Classes\Criterion\CriterionAbstractType;
use Trendix\RankBundle\Classes\Criterion\CriterionTypeInterface;

/**
 * @ORM\Table()
 * @ORM\Entity()
 */
class Option implements \JsonSerializable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="title")
     */
    private $title;

    /**
     * @var float
     * @ORM\Column(name="weight")
     */
    private $weight;

    /**
     * @var Criterion
     * @ORM\ManyToOne(targetEntity="Trendix\RankBundle\Entity\Criterion\SingleOptionCriterion", inversedBy="options")
     */
    private $singleOptionCriterion;

    /**
     * @var Criterion
     * @ORM\ManyToOne(targetEntity="Trendix\RankBundle\Entity\Criterion\MultipleOptionCriterion", inversedBy="options")
     */
    private $multipleOptionCriterion;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Option
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * @param float $weight
     * @return Option
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;
        return $this;
    }

    /**
     * @return Criterion
     */
    public function getSingleOptionCriterion(): Criterion
    {
        return $this->singleOptionCriterion;
    }

    /**
     * @param Criterion $singleOptionCriterion
     * @return Option
     */
    public function setSingleOptionCriterion($singleOptionCriterion)
    {
        $this->singleOptionCriterion = $singleOptionCriterion;
        return $this;
    }

    /**
     * @return Criterion
     */
    public function getMultipleOptionCriterion(): Criterion
    {
        return $this->multipleOptionCriterion;
    }

    /**
     * @param Criterion $multipleOptionCriterion
     * @return Option
     */
    public function setMultipleOptionCriterion($multipleOptionCriterion)
    {
        $this->multipleOptionCriterion = $multipleOptionCriterion;
        return $this;
    }

    /**
     * @return CriterionTypeInterface
     */
    public function getCriterion()
    {
        if ($this->singleOptionCriterion instanceof SingleOptionCriterion) {
            return $this->singleOptionCriterion;
        }

        return $this->multipleOptionCriterion;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'weight' => $this->weight
        ];
    }


}

Entity/Poll/Poll.php
<?php


namespace Trendix\RankBundle\Entity\Poll;

use Doctrine\Common\Collections\ArrayCollection;
use Trendix\AdminBundle\Entity\User;
use Trendix\AdminBundle\Utility\Dates;
use Trendix\RankBundle\Entity\Answer\Answer;
use Trendix\RankBundle\Entity\Rank;
use Doctrine\ORM\Mapping as ORM;
use Trendix\RankBundle\Entity\SupplierClassification;
use Trendix\RankBundle\Entity\Versions\Version;
use Trendix\AdminBundle\EventListener\DiscriminatorEntry;

/**
 * Rank
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Trendix\RankBundle\Entity\Repository\PollRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name = "type", type = "string")
 * @DiscriminatorEntry(value = "poll")
 */
class Poll
{
    const TYPE_EVALUATIONPOLL = 'EVALUATIONPOLL';
    const TYPE_RECURRENTPOLL = 'RECURRENTPOLL';

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Rank
     *
     * @ORM\ManyToOne(targetEntity="Trendix\RankBundle\Entity\Rank", inversedBy="polls")
     */
    private $rank;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="Trendix\AdminBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Trendix\RankBundle\Entity\Answer\Answer", mappedBy="poll", cascade={"persist"})
     */
    private $answers;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $created_at;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updated_at;

    public function __construct()
    {
        $this->created_at = Dates::getDateTimeWithMilisecs();
        $this->updated_at = Dates::getDateTimeWithMilisecs();
        $this->answers = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Rank
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * @param Rank $rank
     * @return Poll
     */
    public function setRank($rank)
    {
        $this->rank = $rank;
        return $this;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return Poll
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getAnswers()
    {
        return $this->answers;
    }

    /**
     * @param Answer $answers
     * @return Poll
     */
    public function setAnswers($answers)
    {
        $this->answers = $answers;
        return $this;
    }

    /**
     * @param Answer $answer
     * @return $this
     */
    public function addAnswer($answer)
    {
        $answer->setPoll($this);
        $this->answers->add($answer);
        return $this;
    }

    /**
     * @param Answer $answer
     * @return $this
     */
    public function removeAnswer($answer)
    {
        if ($this->answers->contains($answer)) {
            $this->answers->removeElement($answer);
        }
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param \DateTime $created_at
     * @return Poll
     */
    public function setCreatedAt( $created_at)
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param \DateTime $updated_at
     * @return Poll
     */
    public function setUpdatedAt( $updated_at)
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    public static function getClassByType($type = '')
    {
        $types = [
            self::TYPE_EVALUATIONPOLL => EvaluationPoll::class,
            self::TYPE_RECURRENTPOLL => RecurrentPoll::class
        ];

        if (!isset($types[$type])) {
            return null;
        }

        return $types[$type];
    }
}

Controller/PollController.php
<?php

namespace Trendix\RankBundle\Controller;

use Trendix\AdminBundle\Controller\TrendixBaseController;
use Trendix\RankBundle\Classes\Rank\CriterionFillerInterface;
use Trendix\RankBundle\Entity\Evaluation\EvaluationPoll;
use Trendix\RankBundle\Entity\Rank;
use Trendix\RankBundle\Form\EvaluationPollFormType;
use Trendix\SubastasBundle\Entity\Proveedor;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PollController
{
    /**
     * @Route("/view/{id}", name="ver_formulario_evaluacion")
     *
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Doctrine\ORM\ORMException
     */
    public function viewEvaluationForm($id)
    {
        $this->sessionStart();

        $proveedor = $this->em->getRepository('TrendixSubastasBundle:Proveedor')->find($id);
        if (!$proveedor instanceof Proveedor) {
            return $this->throwTrendixNotFoundException();
        }

        $formRepo = $this->em->getRepository('TrendixRankBundle:EvaluationForm');
        $pollRepo = $this->em->getRepository('TrendixRankBundle:Evaluation\EvaluationPoll');

        // Añadimos los datos que recibirán todas las vistas
        $this->addData('moduloHomologacionesActivado', $this->validateModuleIsEnabled());
        $this->addData('proveedor', $proveedor);

        $evaluationPoll = $pollRepo->findLastByUser($proveedor->getUsuario());
        // Si no se encuentra formluario de evaluarion mostramos mensaje de que no hay formulario
        if (!$evaluationPoll instanceof EvaluationPoll) {
            $rank = $formRepo->findCurrent();
            if (!$rank instanceof Rank) {
                return $this->render('@TrendixRank/evaluations/poll/empty.html.twig');
            }
            $evaluationPoll = $this->get('evaluation.poll.generator')->createPollFromEvaluation($rank, $proveedor->getUsuario());
        }

        $ranking = $this->get('evaluation.ranking.calculator')->getArrayRankingFromPoll($evaluationPoll);
        $visibilities = $this->get('evaluation.visibilities')->getVisibilities($this->usuario, $evaluationPoll);

        $filler = CriterionFillerInterface::FILLER_BUYER;
        if ($this->usuario->isProveedor()) {
            $filler = CriterionFillerInterface::FILLER_SUPLIER;
        }

        $this->addData('filler', $filler);
        $this->addData('rank', $evaluationPoll->getRank());
        $this->addData('isOlderVersion', $formRepo->isOlderVersion($evaluationPoll->getRank()));
        $this->addData('sections', $pollRepo->findAllCurrentSections($evaluationPoll)); // Prueba de integrar todas las secciones en un mismo arraycollection
        $this->addData('evaluationPoll', $evaluationPoll);
        $this->addData('visibilities', $visibilities);
        $this->addData('proveedor', $proveedor);
        $this->addData('ranking', $ranking);
        $this->addData('classificationSection', $evaluationPoll->getSupplierClassification());
        $this->addData('canFillEvaluationPoll', $this->get('evaluation.access.manager')->canFillEvaluationPoll($this->usuario, $evaluationPoll));

        return $this->render('TrendixRankBundle:evaluations/poll:view.html.twig', $this->getData());
    }

    /**
     * @Route("/fill/{id}", name="rellenar_formulario_evaluacion")
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function pollAction(Request $request, $id)
    {
        $this->sessionStart();

        $currentEvaluation = $this->em->getRepository('TrendixRankBundle:EvaluationForm')->findCurrent();
        $proveedor = $this->em->getRepository('TrendixSubastasBundle:Proveedor')->find($id);
        if (!$proveedor instanceof Proveedor) {
            return $this->throwTrendixNotFoundException();
        }

        $evaluationPoll = $this->get('evaluation.poll.generator')->createPollFromEvaluation($currentEvaluation, $proveedor->getUsuario());
        if (!$this->get('evaluation.access.manager')->canFillEvaluationPoll($this->usuario, $evaluationPoll)) {
            return $this->throwTrendixNotFoundException();
        }

        $sections = $this->em->getRepository('TrendixRankBundle:Evaluation\EvaluationPoll')->findAllCurrentSections($evaluationPoll);
        $visibilities = $this->get('evaluation.visibilities');
        $visibilities->setPoll($evaluationPoll);

        $formOptions = [
            'rank' => $evaluationPoll->getRank(),
            'owner' => $proveedor->getContacto()->getUsuario(),
            'filler' => $this->usuario,
            'em' => $this->em,
            'visibilities' => $visibilities
        ];
        $form = $this->createForm(new EvaluationPollFormType(), $evaluationPoll, $formOptions);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($evaluationPoll);
            $this->em->flush();
            $this->get('session')->getFlashBag()->add('notice', 'evaluations.guardado_correctamente');
            return $this->redirectToRoute('ver_formulario_evaluacion', ['id' => $proveedor->getId()]);
        }

        $visibilities = $this->get('evaluation.visibilities')->getVisibilities($this->usuario, $evaluationPoll);

        $filler = CriterionFillerInterface::FILLER_BUYER;
        if ($this->usuario->isProveedor()) {
            $filler = CriterionFillerInterface::FILLER_SUPLIER;
        }

        $this->addData('filler', $filler);
        $this->addData('visibilities', $visibilities);
        $this->addData('form', $form->createView());
        $this->addData('rank', $currentEvaluation);
        $this->addData('sections', $sections);
        $this->addData('proveedor', $proveedor);
        $this->addData('moduloHomologacionesActivado', true);
        $this->addData('canValidate', $this->get('evaluation.access.manager')->canValidateEvaluationPoll($this->usuario, $evaluationPoll));

        return $this->render('TrendixRankBundle:evaluations/poll:Poll.html.twig', $this->getData());
    }
}

Resources/views/evaluations/poll/Poll.html.twig
{% extends 'TrendixRankBundle:evaluations:EvaluationTabLayout.html.twig' %}

{% set titulo = 'evaluations.form'|trans %}

{% block title %}
    {{ titulo }} - {{ parent() }}
{% endblock %}

{% block status_bar_container %}{% endblock %}

{% block poll_sections_container %}
    {{ form_start(form, {'attr': {class: 'form', id: 'evaluationPoll'}}) }}
    {% for section in sections %}
        {% embed 'TrendixRankBundle:evaluations:SectionBlockLayout.html.twig'
                with {
            'section': section,
            'SupplierEvaluation': form,
            'weight': null,
            'alias': section.numerationalias
        } %}

            {% block evaluation_section_title %}
                <span class="sectionAlias">{{ alias }}</span> - {{ section.title }}
            {% endblock %}

            {% block evaluation_section_weight %}{% endblock %}

            {% block evaluation_section_questions %}
                {% embed 'TrendixRankBundle:evaluations:AnswersResultBlock.html.twig'
                    with {
                    criteria: section.criteria,
                    answers: form.answers,
                } only
                %}
                {% endembed %}
            {% endblock %}
        {% endembed %}
    {% endfor %}

    {% if canValidate and form.expires_at is defined %}
    <div class="block">
        <div class="block-content">{{ form_row(form.expires_at, {attr: {class: 'pickadate'}}) }}</div>
    </div>
    {% endif %}

    {{ form_end(form) }}
{% endblock %}

{% block action_buttons %}
    <a class="btn btn-info" href="{{ path('ver_formulario_evaluacion', {id: proveedor.id}) }}" title="{{ 'str_volver'|trans }}"><i class="icon-arrow-left"></i></a>
    <a class="btn btn-success" href="javascript:$('#evaluationPoll').trigger('submit');" title="{{ 'str_guardar'|trans }}"><i class="icon-save"></i></a>
{% endblock %}

{% block more_scripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('bundles/Admin/plupload/js/plupload.full.min.js') }}"></script>
    {% include 'AdminBundle:Fileupload:generaluploader.js.twig' %}
{% endblock %}

Resources/views/evaluations/poll/empty.html.twig
{%  set mensaje = 'evaluations.sin_formulario' %}
{%  set turnBack = path('ver_proveedor', {'id': proveedor.id}) %}

{% extends 'AdminBundle:Exception:exceptionTemplate.html.twig' %}

{% block pre_content %}{% include 'DirectorioBundle:Proveedor:tabs.html.twig' with { 'tab': 'formulario' , 'proveedor': proveedor } %}{% endblock %}

Resources/views/evaluations/poll/list.html.twig
{% extends 'TrendixRankBundle:evaluations:EvaluationTabLayout.html.twig' %}
{% import _self as macros %}

{% set titulo = 'evaluations.form'|trans %}

{% block title %}
    {{ titulo }} - {{ parent() }}
{% endblock %}

{% block content_body %}
    {% if evaluationPoll is not null %}
    <div class="block">
        <div class="block-header">{{ 'evaluations.evaluation_form'|trans }}</div>
        <div class="block-content no-padding">
            <table class="table table-striped selectable">
                <tbody>
                    <tr class="table-even">
                        <th>{{ 'str_titulo'|trans }}</th>
                        <th>{{ 'str_puntos'|trans }}</th>
                        <th>{{ 'str_estado'|trans }}</th>
                        <th>{{ 'str_valido_hasta'|trans }}</th>
                        <th>{{ 'str_completado'|trans }}</th>
                        <th>{{ 'str_acciones'|trans }}</th>
                    </tr>

                    <tr>
                        <td>{{ 'evaluations.evaluation_form'|trans }}</td>
                        <td>{{ rankingEvaluation.userPercent|formatTrendixAmount }} %</td>
                        <td>{{ rankingEvaluation.statusText|trans }}</td>
                        <td>{{ evaluationPoll.expiresAt|formatTrendixDate|default('--') }}</td>
                        <td>{{ rankingEvaluation.completedPercent|formatTrendixAmount }} %</td>
                        <td class="actions">
                            <a title="{{ 'evaluations.completar_formulario'|trans }}" href="{{ path('rellenar_formulario_evaluacion', {id: proveedor.id}) }}"><i class="zmdi zmdi-edit"></i></a>
                            <a title="{{ 'str_ver'|trans }}" href="{{ path('ver_formulario_evaluacion', {id: proveedor.id}) }}"><i class="zmdi zmdi-eye"></i></a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}

    {% if recurrentForm|length > 0 %}
    <div class="block">
        <div class="block-header">{{ 'evaluations.recurrent_form'|trans }}</div>
        <div class="block-content no-padding">
            <table class="table table-striped selectable">
                <tbody>
                    <tr class="table-even">
                        <th>{{ 'str_titulo'|trans }}</th>
                        <th>{{ 'str_puntos'|trans }}</th>
                        <th>{{ 'str_estado'|trans }}</th>
                        <th>{{ 'evaluations.next_request'|trans }}</th>
                        <th>{{ 'str_completado'|trans }}</th>
                        <th>{{ 'str_acciones'|trans }}</th>
                    </tr>

                    {% for r in recurrentForm %}
                    <tr>
                        <td>{{ r.title }}</td>
                        <td>{{ recurrentRanking[r.id].userPercent|formatTrendixAmount }} %</td>
                        <td>{{ recurrentRanking[r.id].statusText|trans }}</td>
                        <td>{{ r.nextRequest|formatTrendixDate }}</td>
                        <td>{{ recurrentRanking[r.id].completedPercent|formatTrendixAmount }} %</td>
                        <td class="actions">
                            <a title="{{ 'evaluations.completar_formulario'|trans }}" href="{{ path('rellenar_formulario_recurrente', {id: r.id, provId: proveedor.id}) }}"><i class="zmdi zmdi-edit"></i></a>
                            <a title="{{ 'str_ver'|trans }}" href="{{ path('ver_formulario_recurrente', {id: recurrentRanking[r.id].poll.id}) }}"><i class="zmdi zmdi-eye"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% macro mes(number) %}
    {% if number == 1 %}{{ 'str_mensual'|trans }}
    {% elseif  number == 3 %}{{ 'str_trimestral'|trans }}
    {% elseif number == 6 %}{{ 'str_semestral'|trans }}
    {% else %}{{ number }} {{ 'evaluations.meses'|trans }}
    {% endif %}
{% endmacro %}

Resources/views/evaluations/poll/view.html.twig
{% extends 'TrendixRankBundle:evaluations:EvaluationTabLayout.html.twig' %}

{% set titulo = 'evaluations.form'|trans %}

{% block title %}
    {{ titulo }} - {{ parent() }}
{% endblock %}

{% if filler == 'proveedor' %}
    {% set percent = null %}
{% else %}
    {% set percent = ranking['userPercent']|formatTrendixAmount ~ '%' %}
{% endif %}

{% block status_bar_container %}
{% include ':helpers:StatusBar.html.twig' with {
    status: ranking.status,
    leftData: ranking.statusText|trans,
    rightData: percent
} only %}

    {% if isOlderVersion %}
    <div class="alert alert-info">
        <h3>{{ 'evaluations.older_version'|trans }}</h3>
        <p>{{ 'evaluations.older_version_info'|trans }}</p>
    </div>
    {% endif %}
{% endblock %}

{% block poll_sections_container %}
    {% for section in sections if visibilities[section.id]['visible']%}
        {% embed 'TrendixRankBundle:evaluations:SectionBlockLayout.html.twig'
            with {
            'section': section,
            'SupplierEvaluation': evaluationPoll,
            'weight': section.weight,
            'alias': section.numerationalias
        } %}
            {% block evaluation_section_title %}
                <span class="sectionAlias">{{ alias }}</span> - {{ section.title }}
            {% endblock %}

            {% block evaluation_section_questions %}
                {% embed 'TrendixRankBundle:evaluations:AnswersResultBlock.html.twig'
                    with {
                    criteria: section.criteria,
                    answers: evaluationPoll.answers,
                    filler: filler,
                    ranking: ranking['sections'][section.id],
                    visibilities: visibilities[section.id]['criteria']
                } only
                %}
                    {% block questions_list_bar %}
                        <div class="bar grey row-fluid">
                            <div class="col-md-7">{{ 'evaluations.questions'|trans }}</div>
                            {% if filler == 'comprador' %}
                            <div class="col-md-2">{{ 'evaluations.answered_by'|trans }}</div>
                            <div class="col-md-1">{{ 'evaluations.filler'|trans }}</div>
                            <div class="col-md-2">{{ 'str_puntos'|trans }}</div>
                            {% endif %}
                        </div>
                    {% endblock %}

                    {% block answer_block %}
                        {% include 'TrendixRankBundle:evaluations:answerview/'~ currentAnswer.criterion.type|camelcase ~'View.html.twig'
                            with {
                            answer: currentAnswer,
                            ranking: ranking['criteria'][currentAnswer.criterion.id],
                            filler: filler,
                            visible: visibilities[currentAnswer.criterion.id]
                        }
                        %}
                    {% endblock %}
                {% endembed %}
            {% endblock %}
        {% endembed %}
    {% endfor %}
{% endblock %}

{% block action_buttons %}
    {% if canFillEvaluationPoll %}
    <a class="btn btn-success" href="{{ path('rellenar_formulario_evaluacion', {id: proveedor.id}) }}" title="{{ 'str_editar'|trans }}"><i class="zmdi zmdi-edit"></i></a>
    {% endif %}
{% endblock %}